bugfix/AB#107
starwit/lj-projectbuilder pull request #242
Opened 2022-01-26 22:10 UTC by DerCed

allowing to add max and min to string

## Description
Fixes AB#107

## Motivation and Context
String length should be definable

## How has this been tested?
Local browser

## Screenshots (if appropriate):

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-01-26 22:17 UTC, witchpou requested changes

2022-01-26 22:17 UTC, witchpou commented on webclient/app/src/app/commons/entityDialog/EntityDialog.jsx
> +            allowMin: true,
die Felder für String sollten auf  minlengh und maxlength gemappt werden...ist das berücksichtigt?           
"fieldValidateRules": [
                "required",
                "minlength",
                "maxlength"
            ],

2022-01-27 07:39 UTC, DerCed commented on webclient/app/src/app/commons/entityDialog/EntityDialog.jsx
> +            allowMin: true,
Durch die Felder kannst du einstellen, ob min und max eingegeben werden kann. Also jetzt sind die beiden Felder frei und kannst Daten wir bei z.B. Integer eingeben.

2022-01-27 12:29 UTC, witchpou commented on webclient/app/src/app/commons/entityDialog/EntityDialog.jsx
> +            allowMin: true,
das beantwortet die Frage nicht - das mapping sollte so aussehen:
{
    "name": "MyTestEntity",
    "fields": [
        {
            "fieldName": "testField",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": 2,
            "fieldValidateRulesMaxlength": 300
        },
        {
            "fieldName": "testField2",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required",
                "min",
                "max"
            ],
            "fieldValidateRulesMin": 0,
            "fieldValidateRulesMax": 200
        }
    ]
}

2022-03-15 20:16 UTC, DerCed commented
@witchpou is this implemented with #255 ? Then I could close this PR

2022-03-18 17:53 UTC, closed without merging