bugfix/AB#110
starwit/lj-projectbuilder pull request #243
Opened 2022-01-26 22:40 UTC by DerCed

## Description
Added Entity title to EntityDialog Title
AB#110

## Motivation and Context
Request by Product Owner

## How has this been tested?
Local Browser

## Screenshots (if appropriate):

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-01-26 23:36 UTC, witchpou commented on webclient/app/src/localization/translations-de-DE.js
> +    "entityDialog.editDomain": "{{entityName}} bearbeiten.",
its better to call it entity than domain
```suggestion
    "entityDialog.editEntity": "{{entityName}} bearbeiten.",
```

2022-01-26 23:36 UTC, witchpou commented on webclient/app/src/localization/translations-en-EN.js
> +    "entityDialog.editDomain": "Edit {{entityName}}.",
```suggestion
    "entityDialog.editEntity": "Edit {{entityName}}.",
```

2022-01-26 23:37 UTC, witchpou commented on webclient/app/src/app/commons/entityDialog/EntityDialog.jsx
> +                    {t("entityDialog.editDomain", {entityName: entity.name})}
```suggestion
                    {t("entityDialog.editEntity", {entityName: entity.name})}
```

2022-01-26 23:39 UTC, witchpou requested changes
Domain -> Entity

2022-01-27 07:38 UTC, DerCed commented
> Domain -> Entity

Which Format do you want exactly?
Shall I rename all Domain references to Entity?

2022-01-27 12:26 UTC, witchpou approved these changes

2022-01-28 16:08 UTC, merged