refactor: ab#209 extract general styles to general style sheet
starwit/lj-projectbuilder pull request #302
Opened 2022-04-13 08:37 UTC by DerCed

## Description
Moved/Extracted/Rewritten styles

## Motivation and Context
Duplicate code

## How has this been tested?
Go through application

## Screenshots (if appropriate):

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-04-13 08:38 UTC, DerCed commented
@witchpou Ich würde das gerne mit dir nochmal besprechen wollen - also WIP!

2022-04-13 09:22 UTC, witchpou commented
> @witchpou Ich würde das gerne mit dir nochmal besprechen wollen - also WIP!

machen wir

2022-04-14 14:05 UTC, witchpou requested changes

2022-04-14 14:05 UTC, witchpou commented on webclient/app/src/app/features/apps/entities/entityCard/EntityCard.jsx
> +                <Statement message={t("entity.fields.empty")}/>
das sieht aber so schon besser aus...

2022-04-14 17:08 UTC, DerCed commented on webclient/app/src/app/commons/statement/Statement.jsx
> +    const statementStyles = StatementStyles({height: (enableSpacing && spacingHeight ? spacingHeight : "100%")});
Bezogen auf die height?

2022-04-20 18:53 UTC, DerCed commented on webclient/app/src/app/commons/statement/Statement.jsx
> +    const statementStyles = StatementStyles({height: (enableSpacing && spacingHeight ? spacingHeight : "100%")});
Die Abfrage noch in die Styling Komponente laden

2022-04-21 17:18 UTC, merged