feat: AB#239 Add Hosted Documentation
starwit/lj-projectbuilder pull request #309
Opened 2022-04-24 20:40 UTC by DerCed

Added Jekyll and MKDocs

## Description

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-05-05 07:36 UTC, witchpou reviewed
Kannst du bitte noch eine Beschreibung einfügen, wie man die Dokumentation testet / damit umgeht wenn man etwas hinzufügt. z.B. Wie es bei jHipster ist: https://github.com/jhipster/jhipster.github.io

2022-05-05 07:36 UTC, witchpou commented on docs/architecture.md
> -The UI logic is placed in the webclient project. ReactJS is used. The Frontend is utilized with [Material-UI](https://www.mui.com) and its design structure (mostly based on [JSS](https://cssinjs.org/
wieso werden hier Zeilenumbrüche hinzugefügt?

2022-05-05 07:36 UTC, witchpou commented on docs/architecture.md
> +Yet still a lot of boilerplate code needs to be written and creating JEE application quickly remains a challenge.
Das ist so für mich nicht handhabbar. Der muss die Zeilenumbrüche von allein finden

2022-05-05 07:36 UTC, witchpou commented on docs/Gemfile.lock
> +GEM
das sieht für mich generiert aus und der Name deutet darauf hin, dass es vielleicht nicht im Repo liegen sollte.

2022-05-05 07:36 UTC, witchpou commented on README.md
> +* [build and release project](docs-mkdocs/build-release-mgmt.md)
der Ordner sollte docs heißen...so kann man die readmes ja nicht mehr lesen, oder?

2022-05-05 07:36 UTC, witchpou commented on README.md
> +<p align="center"><img src="docs-mkdocs/imgs/lJProjectBuilder.png" alt="drawing" style="width:50%;"/></p>
die Bilder werden leider nicht angezeigt

2022-05-05 07:38 UTC, witchpou requested changes
bitte auch nochmal die Akzeptanzkriterien des Tickets checken. Siehe auch https://fiware-requirements.readthedocs.io/en/latest/development/index.html#documentation

2022-05-05 07:42 UTC, witchpou requested changes
Das momentane Theme ist auch noch unübersichtlich. So würd ich das ungern veröffentlichen - dann lieber die puren readme-Dateien. Kannst du bitte noch einmal schauen, ob es da etwas mit Menüleiste Links gibt. Kann auch in einem separaten Ticket geschehen.

2022-05-05 07:48 UTC, witchpou requested changes
Kannst du bitte die unnötigen Änderungen in den readme-dateien rückgängig machen. Ich bekomme sonst massive merge-Konflikte

2022-05-05 07:55 UTC, witchpou requested changes

2022-05-05 07:55 UTC, witchpou commented on docs/index.md
> +---
Diese Datei ist doppelt (siehe ../readme.md)

2022-05-05 20:01 UTC, DerCed commented on docs/architecture.md
> +Yet still a lot of boilerplate code needs to be written and creating JEE application quickly remains a challenge.
Wie meinst du das?

2022-05-05 20:02 UTC, DerCed commented
> 

Hast du schon neue Docs Dateien angefertigt?

2022-05-09 18:16 UTC, witchpou commented
> Das momentane Theme ist auch noch unübersichtlich. So würd ich das ungern veröffentlichen - dann lieber die puren readme-Dateien. Kannst du bitte noch einmal schauen, ob es da etwas mit Menüleiste Links gibt. Kann auch in einem separaten Ticket geschehen.

-> new ticket

2022-05-16 18:19 UTC, witchpou approved these changes

2022-05-16 18:21 UTC, merged