refactor: AB#240 extract commons lib
starwit/lj-projectbuilder pull request #320
Opened 2022-05-08 19:37 UTC by DerCed

Moved Loading spinner to external package (Demo only)

## Description
Exported Loading Spinner to external package (Demo only)

## Motivation and Context
Components are used multiple times. This creates redundancies 

## How has this been tested?
Exported loading spinner to external package 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-05-20 20:01 UTC, DerCed commented on webclient/app/package.json
> +    "@starwit/frontend-commons": "^0.0.1-dev4",
```suggestion
    "@starwit/frontend-commons": "^0.0.1-dev1",
```

2022-05-28 11:34 UTC, witchpou requested changes
es baut noch nicht - ich schau mir die package json gleich mal an

2022-05-28 11:34 UTC, witchpou commented on webclient/app/src/app/features/apps/appSteps/AppConclusion.jsx
> +import PropTypes from "prop-types";
weswegen diese Anpassung notwendig war, verstehe ich nicht

2022-05-28 11:41 UTC, witchpou requested changes
der code unter react-starwit entspricht weder den unter reacthook-spring-template noch den unter lj-projectbuilder. Das ist nicht sauber miteinander abgeglichen, so dass keines der beiden Projekte funktionieren wird. Ich habe es noch einmal abgeglichen. Bitte unveränderten code von reacthook-spring-template verwenden! Schnittstellendefinitionen können wir hinzufügen, wenn alles läuft. Ich mache einen entsprechenden PR.

2022-05-28 14:30 UTC, DerCed commented
> der code unter react-starwit entspricht weder den unter reacthook-spring-template noch den unter lj-projectbuilder. Das ist nicht sauber miteinander abgeglichen, so dass keines der beiden Projekte funktionieren wird. Ich habe es noch einmal abgeglichen. Bitte unveränderten code von reacthook-spring-template verwenden! Schnittstellendefinitionen können wir hinzufügen, wenn alles läuft. Ich mache einen entsprechenden PR.

Der Code den ich da eingecheckt habe, ist von dem Projectbuilder. Ich habe Komponenten ausgelassen, die nicht gültig waren bzw nicht mit den Abhängigkeiten die ich gefunden hatte, gültig waren. Wenn sich da was getan hat, kann ich die reinnehmen.

Die Methodenspezifikationen würde ich aber gerne beim ersten Release drinnen haben. Ansonsten hat man gar keine Dokumentation, was beim entwickeln blöd wäre

2022-05-28 14:31 UTC, DerCed commented on webclient/app/src/app/features/apps/appSteps/AppConclusion.jsx
> +import PropTypes from "prop-types";
Ansonsten baut der Code nicht. Proptypes waren unten definiert aber nicht importiert. Irgendwer hat das rausgenommen...

2022-05-30 19:42 UTC, DerCed commented on webclient/app/package.json
> +    "@starwit/frontend-commons": "^0.0.1-dev1",
```suggestion
    "@starwit/react-starwit": "^0.0.1-dev1",
```

2022-05-30 20:14 UTC, merged

2022-05-30 20:14 UTC, DerCed commented
@witchpou works now! merged in develop